"""Default monster catalog for database seeding."""

DEFAULT_MONSTERS = [
    {"monster_level": 70, "monster_name": 'Ancient Bat', "monster_health": 3300, "monster_image": 'ancient-bat.png'},
    {"monster_level": 90, "monster_name": 'Ancient Cyclops', "monster_health": 5000, "monster_image": 'ancient-cyclops.png'},
    {"monster_level": 120, "monster_name": 'Ancient War Bat', "monster_health": 30000, "monster_image": 'ancient-war-bat.gif'},
    {"monster_level": 110, "monster_name": 'Anubis Elite', "monster_health": 10000, "monster_image": 'anubis-elite.png'},
    {"monster_level": 90, "monster_name": 'Anubis', "monster_health": 3300, "monster_image": 'anubis.png'},
    {"monster_level": 75, "monster_name": 'Arosite Scarab', "monster_health": 4500, "monster_image": 'arosite-scarab.png'},
    {"monster_level": 110, "monster_name": 'Baby Dragon', "monster_health": 6500, "monster_image": 'baby-dragon.png'},
    {"monster_level": 10, "monster_name": 'Baby Seedling', "monster_health": 220, "monster_image": 'baby-seedling.png'},
    {"monster_level": 1, "monster_name": 'Bat', "monster_health": 45, "monster_image": 'bat.png'},
    {"monster_level": 120, "monster_name": 'Brown Snake', "monster_health": 7500, "monster_image": 'brown-snake.png'},
    {"monster_level": 80, "monster_name": 'Cactus Soldier', "monster_health": 3200, "monster_image": 'cactus-soldier.png'},
    {"monster_level": 43, "monster_name": 'Cave Bat', "monster_health": 1250, "monster_image": 'cave-bat.png'},
    {"monster_level": 34, "monster_name": 'Cave Spider', "monster_health": 820, "monster_image": 'cave-spider.png'},
    {"monster_level": 1, "monster_name": 'Chicken', "monster_health": 30, "monster_image": 'chicken.png'},
    {"monster_level": 92, "monster_name": 'Corrupted Venomling', "monster_health": 4500, "monster_image": 'corrupted-venomling.png'},
    {"monster_level": 14, "monster_name": 'Cow', "monster_health": 325, "monster_image": 'cow.png'},
    {"monster_level": 400, "monster_name": 'Cursed Totem', "monster_health": 30000, "monster_image": 'cursed-totem.png'},
    {"monster_level": 105, "monster_name": 'Defiled Scarab', "monster_health": 6500, "monster_image": 'defiled-scarab.png'},
    {"monster_level": 57, "monster_name": 'Desert Raptor', "monster_health": 1980, "monster_image": 'desert-raptor.png'},
    {"monster_level": 125, "monster_name": 'Disdained Venomling', "monster_health": 8000, "monster_image": 'disdained-venomling.png'},
    {"monster_level": 8, "monster_name": 'Fishing Spider', "monster_health": 190, "monster_image": 'fishing-spider.png'},
    {"monster_level": 15, "monster_name": 'Forest Bat', "monster_health": 350, "monster_image": 'forest-bat.png'},
    {"monster_level": 53, "monster_name": 'Forest Fiend', "monster_health": 2000, "monster_image": 'forest-fiend.png'},
    {"monster_level": 12, "monster_name": 'Forest Spider', "monster_health": 250, "monster_image": 'forest-spider.png'},
    {"monster_level": 62, "monster_name": 'Giant Hornet', "monster_health": 2900, "monster_image": 'giant-hornet.png'},
    {"monster_level": 110, "monster_name": 'Gold Snake', "monster_health": 7500, "monster_image": 'gold-snake.png'},
    {"monster_level": 330, "monster_name": 'Golem', "monster_health": 45000, "monster_image": 'golem.gif'},
    {"monster_level": 100, "monster_name": 'Golemite Fiend', "monster_health": 5800, "monster_image": 'golemite-fiend.png'},
    {"monster_level": 130, "monster_name": 'Ice Demon', "monster_health": 35000, "monster_image": 'ice-demon.gif'},
    {"monster_level": 47, "monster_name": 'Ice Fiend', "monster_health": 1800, "monster_image": 'ice-fiend.png'},
    {"monster_level": 73, "monster_name": 'Ice Raptor', "monster_health": 3700, "monster_image": 'ice-raptor.png'},
    {"monster_level": 21, "monster_name": 'Ice Slime', "monster_health": 500, "monster_image": 'ice-slime.png'},
    {"monster_level": 28, "monster_name": 'Ice Spider', "monster_health": 650, "monster_image": 'ice-spider.png'},
    {"monster_level": 65, "monster_name": 'Juvenile Venomling', "monster_health": 3200, "monster_image": 'juvenile-venomling.png'},
    {"monster_level": 65, "monster_name": 'Luminant Slime', "monster_health": 3000, "monster_image": 'luminant-slime.png'},
    {"monster_level": 90, "monster_name": 'Magnetite Scarab', "monster_health": 5800, "monster_image": 'magnetite-scarab.png'},
    {"monster_level": 400, "monster_name": 'Mummy', "monster_health": 170000, "monster_image": 'mummy.gif'},
    {"monster_level": 10, "monster_name": 'Mushroom', "monster_health": 215, "monster_image": 'mushroom.png'},
    {"monster_level": 70, "monster_name": 'Nature Elder', "monster_health": 15000, "monster_image": 'nature-elder.gif'},
    {"monster_level": 10, "monster_name": 'Nydarax', "monster_health": 0, "monster_image": 'nydarax.gif'},
    {"monster_level": 88, "monster_name": 'Phantom Fiend', "monster_health": 4500, "monster_image": 'phantom-fiend.png'},
    {"monster_level": 80, "monster_name": 'Phantom Flame', "monster_health": 3750, "monster_image": 'phantom-flame.png'},
    {"monster_level": 100, "monster_name": 'Poltergeist', "monster_health": 5000, "monster_image": 'poltergeist.png'},
    {"monster_level": 135, "monster_name": 'Purple Snake', "monster_health": 8500, "monster_image": 'purple-snake.png'},
    {"monster_level": 110, "monster_name": 'Rageful Venomling', "monster_health": 7500, "monster_image": 'rageful-venomling.png'},
    {"monster_level": 49, "monster_name": 'Raptor', "monster_health": 1875, "monster_image": 'raptor.png'},
    {"monster_level": 300, "monster_name": 'Reanimated Soul', "monster_health": 600000, "monster_image": 'reanimated_soul.gif'},
    {"monster_level": 110, "monster_name": 'Rock Demon', "monster_health": 25000, "monster_image": 'rock-demon.gif'},
    {"monster_level": 60, "monster_name": 'Rock Fiend', "monster_health": 2850, "monster_image": 'rock-fiend.png'},
    {"monster_level": 50, "monster_name": 'Ruby Scarab', "monster_health": 1900, "monster_image": 'ruby-scarab.png'},
    {"monster_level": 150, "monster_name": 'Sandstone Golem', "monster_health": 13000, "monster_image": 'sandstone-golem.png'},
    {"monster_level": 40, "monster_name": 'Sapphire Scarab', "monster_health": 950, "monster_image": 'sapphire-scarab.png'},
    {"monster_level": 45, "monster_name": 'Scorpion', "monster_health": 1400, "monster_image": 'scorpion.png'},
    {"monster_level": 40, "monster_name": 'Seed Guardian', "monster_health": 1600, "monster_image": 'seed-guardian.png'},
    {"monster_level": 25, "monster_name": 'Seedling', "monster_health": 500, "monster_image": 'seedling.png'},
    {"monster_level": 250, "monster_name": 'Shadow Demon', "monster_health": 50000, "monster_image": 'shadow-demon.gif'},
    {"monster_level": 50, "monster_name": 'Shadow Fiend', "monster_health": 2150, "monster_image": 'shadow-fiend.png'},
    {"monster_level": 78, "monster_name": 'Shadow Flame', "monster_health": 2675, "monster_image": 'shadow-flame.png'},
    {"monster_level": 35, "monster_name": 'Skeletal Bat', "monster_health": 900, "monster_image": 'skeletal-bat.png'},
    {"monster_level": 30, "monster_name": 'Skeletal Snake', "monster_health": 730, "monster_image": 'skeletal-snake.png'},
    {"monster_level": 4, "monster_name": 'Slime', "monster_health": 120, "monster_image": 'slime.png'},
    {"monster_level": 18, "monster_name": 'Snow Bat', "monster_health": 420, "monster_image": 'snow-bat.png'},
    {"monster_level": 25, "monster_name": 'Snowman', "monster_health": 590, "monster_image": 'snowman.png'},
    {"monster_level": 85, "monster_name": 'Spectral Fiend', "monster_health": 3950, "monster_image": 'spectral-fiend.png'},
    {"monster_level": 75, "monster_name": 'Spectral Flame', "monster_health": 3600, "monster_image": 'spectral-flame.png'},
    {"monster_level": 115, "monster_name": 'Spinus', "monster_health": 0, "monster_image": 'spinus.gif'},
    {"monster_level": 100, "monster_name": 'Tormented Venomling', "monster_health": 6000, "monster_image": 'tormented-venomling.png'},
    {"monster_level": 350, "monster_name": 'Umbra', "monster_health": 0, "monster_image": 'umbra.gif'},
    {"monster_level": 25, "monster_name": 'War Bat', "monster_health": 2500, "monster_image": 'war-bat.gif'},
    {"monster_level": 100, "monster_name": 'Bryomera', "monster_health": 5000, "monster_image": ''},
    {"monster_level": 95, "monster_name": 'Golemite Bat', "monster_health": 5300, "monster_image": ''},
    {"monster_level": 100, "monster_name": 'War Bear', "monster_health": 0, "monster_image": ''},
]

__all__ = ["DEFAULT_MONSTERS"]
