"""Default monster catalog for database seeding."""

DEFAULT_MONSTERS = [
    {"monster_level": 1, "monster_name": "Bat", "monster_image": "bat.png"},
    {"monster_level": 1, "monster_name": "Chicken", "monster_image": "chicken.png"},
    {"monster_level": 4, "monster_name": "Slime", "monster_image": "slime.png"},
    {"monster_level": 8, "monster_name": "Fishing Spider", "monster_image": "fishing-spider.png"},
    {"monster_level": 10, "monster_name": "Mushroom", "monster_image": "mushroom.png"},
    {"monster_level": 10, "monster_name": "Baby Seedling", "monster_image": "baby-seedling.png"},
    {"monster_level": 12, "monster_name": "Forest Spider", "monster_image": "forest-spider.png"},
    {"monster_level": 14, "monster_name": "Cow", "monster_image": "cow.png"},
    {"monster_level": 15, "monster_name": "Forest Bat", "monster_image": "forest-bat.png"},
    {"monster_level": 18, "monster_name": "Snow Bat", "monster_image": "snow-bat.png"},
    {"monster_level": 21, "monster_name": "Ice Slime", "monster_image": "ice-slime.png"},
    {"monster_level": 25, "monster_name": "Snowman", "monster_image": "snowman.png"},
    {"monster_level": 25, "monster_name": "Seedling", "monster_image": "seedling.png"},
    {"monster_level": 28, "monster_name": "Ice Spider", "monster_image": "ice-spider.png"},
    {"monster_level": 30, "monster_name": "Skeletal Snake", "monster_image": "skeletal-snake.png"},
    {"monster_level": 34, "monster_name": "Cave Spider", "monster_image": "cave-spider.png"},
    {"monster_level": 35, "monster_name": "Skeletal Bat", "monster_image": "skeletal-bat.png"},
    {"monster_level": 40, "monster_name": "Sapphire Scarab", "monster_image": "sapphire-scarab.png"},
    {"monster_level": 43, "monster_name": "Cave Bat", "monster_image": "cave-bat.png"},
    {"monster_level": 45, "monster_name": "Scorpion", "monster_image": "scorpion.png"},
    {"monster_level": 47, "monster_name": "Ice Fiend", "monster_image": "ice-fiend.png"},
    {"monster_level": 49, "monster_name": "Raptor", "monster_image": "raptor.png"},
    {"monster_level": 50, "monster_name": "Ruby Scarab", "monster_image": "ruby-scarab.png"},
    {"monster_level": 50, "monster_name": "Shadow Fiend", "monster_image": "shadow-fiend.png"},
    {"monster_level": 53, "monster_name": "Forest Fiend", "monster_image": "forest-fiend.png"},
    {"monster_level": 57, "monster_name": "Desert Raptor", "monster_image": "desert-raptor.png"},
    {"monster_level": 60, "monster_name": "Rock Fiend", "monster_image": "rock-fiend.png"},
    {"monster_level": 62, "monster_name": "Giant Hornet", "monster_image": "giant-hornet.png"},
    {"monster_level": 65, "monster_name": "Juvenile Venomling", "monster_image": "juvenile-venomling.png"},
    {"monster_level": 65, "monster_name": "Luminant Slime", "monster_image": "luminant-slime.png"},
    {"monster_level": 70, "monster_name": "Ancient Bat", "monster_image": "ancient-bat.png"},
    {"monster_level": 73, "monster_name": "Ice Raptor", "monster_image": "ice-raptor.png"},
    {"monster_level": 75, "monster_name": "Arosite Scarab", "monster_image": "arosite-scarab.png"},
    {"monster_level": 75, "monster_name": "Spectral Flame", "monster_image": "spectral-flame.png"},
    {"monster_level": 78, "monster_name": "Shadow Flame", "monster_image": "shadow-flame.png"},
    {"monster_level": 80, "monster_name": "Cactus Soldier", "monster_image": "cactus-soldier.png"},
    {"monster_level": 80, "monster_name": "Phantom Flame", "monster_image": "phantom-flame.png"},
    {"monster_level": 85, "monster_name": "Spectral Fiend", "monster_image": "spectral-fiend.png"},
    {"monster_level": 88, "monster_name": "Phantom Fiend", "monster_image": "phantom-fiend.png"},
    {"monster_level": 90, "monster_name": "Ancient Cyclops", "monster_image": "ancient-cyclops.png"},
    {"monster_level": 90, "monster_name": "Anubis", "monster_image": "anubis.png"},
    {"monster_level": 90, "monster_name": "Magnetite Scarab", "monster_image": "magnetite-scarab.png"},
    {"monster_level": 92, "monster_name": "Corrupted Venomling", "monster_image": "corrupted-venomling.png"},
    {"monster_level": 95, "monster_name": "Golemite Bat", "monster_image": ""},
    {"monster_level": 100, "monster_name": "Golemite Fiend", "monster_image": "golemite-fiend.png"},
    {"monster_level": 100, "monster_name": "Poltergeist", "monster_image": "poltergeist.png"},
    {"monster_level": 100, "monster_name": "Tormented Venomling", "monster_image": "tormented-venomling.png"},
    {"monster_level": 105, "monster_name": "Defiled Scarab", "monster_image": "defiled-scarab.png"},
    {"monster_level": 110, "monster_name": "Anubis Elite", "monster_image": "anubis-elite.png"},
    {"monster_level": 110, "monster_name": "Baby Dragon", "monster_image": "baby-dragon.png"},
    {"monster_level": 110, "monster_name": "Gold Snake", "monster_image": "gold-snake.png"},
    {"monster_level": 110, "monster_name": "Rageful Venomling", "monster_image": "rageful-venomling.png"},
    {"monster_level": 120, "monster_name": "Brown Snake", "monster_image": "brown-snake.png"},
    {"monster_level": 125, "monster_name": "Disdained Venomling", "monster_image": "disdained-venomling.png"},
    {"monster_level": 135, "monster_name": "Purple Snake", "monster_image": "purple-snake.png"},
    {"monster_level": 150, "monster_name": "Sandstone Golem", "monster_image": "sandstone-golem.png"},
    {"monster_level": 40, "monster_name": "Seed Guardian", "monster_image": "seed-guardian.png"},
    {"monster_level": 400, "monster_name": "Cursed Totem", "monster_image": "cursed-totem.png"},

    {"monster_level": 25, "monster_name": "War Bat", "monster_image": "war-bat.gif"},
    {"monster_level": 70, "monster_name": "Nature Elder", "monster_image": "nature-elder.gif"},
    {"monster_level": 110, "monster_name": "Rock Demon", "monster_image": "rock-demon.gif"},
    {"monster_level": 115, "monster_name": "Spinus", "monster_image": "spinus.gif"},
    {"monster_level": 120, "monster_name": "Ancient War Bat", "monster_image": "ancient-war-bat.gif"},
    {"monster_level": 130, "monster_name": "Ice Demon", "monster_image": "ice-demon.gif"},
    {"monster_level": 250, "monster_name": "Shadow Demon", "monster_image": "shadow-demon.gif"},
    {"monster_level": 300, "monster_name": "Reanimated Soul", "monster_image": "reanimated_soul.gif"},
    {"monster_level": 330, "monster_name": "Golem", "monster_image": "golem.gif"},
    {"monster_level": 350, "monster_name": "Umbra", "monster_image": "umbra.gif"},
    {"monster_level": 400, "monster_name": "Mummy", "monster_image": "mummy.gif"},
    {"monster_level": 10, "monster_name": "Nydarax", "monster_image": "nydarax.gif"},
    {"monster_level": 100, "monster_name": "Bryomera", "monster_image": ""},
    {"monster_level": 100, "monster_name": "War Bear", "monster_image": ""},
]

__all__ = ["DEFAULT_MONSTERS"]
