# utils/default_data.py
DEFAULT_ITEMS = {
    "Mining (Ores)": [
        {"item_name": "Tin Ore", "item_price": 1000},
        {"item_name": "Copper Ore", "item_price": 1000},
        {"item_name": "Iron Ore", "item_price": 1500},
        {"item_name": "Salt", "item_price": 4000},
        {"item_name": "Coal", "item_price": 3500},
        {"item_name": "Silver Ore", "item_price": 4000},
        {"item_name": "Crimsteel Ore", "item_price": 4500},
        {"item_name": "Gold Ore", "item_price": 5000},
        {"item_name": "Pink Salt", "item_price": 7000},
        {"item_name": "Mythan Ore", "item_price": 7000},
        {"item_name": "Sandstone", "item_price": 10000},
        {"item_name": "Cobalt Ore", "item_price": 9000},
        {"item_name": "Varaxium", "item_price": 12000},
        {"item_name": "Black Salt", "item_price": 9000},
        {"item_name": "Magic Ore", "item_price": 5000},
        {"item_name": "Obsidian Ore", "item_price": 22000},
    ],
    "Smithing (Bars)": [
        {"item_name": "Bronze Bar", "item_price": 2500},
        {"item_name": "Iron Bar", "item_price": 3500},
        {"item_name": "Steel Bar", "item_price": 6000},
        {"item_name": "Crimsteel Bar", "item_price": 18000},
        {"item_name": "Silver Bar", "item_price": 20000},
        {"item_name": "Gold Nugget", "item_price": 50000},
        {"item_name": "Gold Bar", "item_price": 1200000},
        {"item_name": "Mythan Bar", "item_price": 110000},
        {"item_name": "Cobalt Bar", "item_price": 130000},
        {"item_name": "Varaxite Bar", "item_price": 160000},
        {"item_name": "Magic Bar", "item_price": 60000},
        {"item_name": "Obsidian Bar", "item_price": 3000000},
        {"item_name": "Defiled Bar", "item_price": 5000000},
    ],
    "Woodcutting (Logs)": [
        {"item_name": "Pine Log", "item_price": 2000},
        {"item_name": "Dead Log", "item_price": 2500},
        {"item_name": "Birch Log", "item_price": 3000},
        {"item_name": "Applewood", "item_price": 3500},
        {"item_name": "Willow Log", "item_price": 4000},
        {"item_name": "Oak Log", "item_price": 4500},
        {"item_name": "Chestnut Log", "item_price": 6000},
        {"item_name": "Maple Log", "item_price": 8000},
        {"item_name": "Olive Log", "item_price": 10000},
        {"item_name": "Stinkwood", "item_price": 10000},
        {"item_name": "Magic Log", "item_price": 2500},
        {"item_name": "Palmwood", "item_price": 4000},
        {"item_name": "Pearwood", "item_price": 7000},
        {"item_name": "Limewood", "item_price": 5000},
    ],
    "Crafting (Relics)": [
        {"item_name": "Relic of Accuracy", "item_price": 3500},
        {"item_name": "Relic of Guarding", "item_price": 3500},
        {"item_name": "Relic of Healing", "item_price": 4000},
        {"item_name": "Relic of Wealth", "item_price": 4000},
        {"item_name": "Relic of Power", "item_price": 6000},
        {"item_name": "Relic of Nature", "item_price": 5500},
        {"item_name": "Relic of Fire", "item_price": 7000},
        {"item_name": "Relic of Damage", "item_price": 8000},
        {"item_name": "Relic of Leeching", "item_price": 6000},
        {"item_name": "Relic of Experience", "item_price": 12000},
        {"item_name": "Relic of Wisdom", "item_price": 15000},
        {"item_name": "Relic of Ice", "item_price": 4500},
        {"item_name": "Relic of Curse", "item_price": 3500},
        {"item_name": "Relic of Efficiency", "item_price": 5000},
        {"item_name": "Relic of Affliction", "item_price": 5000},
        {"item_name": "Ancient Tablet", "item_price": 4000},
    ],
    "Fishing (Baits, Fishes, & Meats)": [
        {"item_name": "Earthworm", "item_price": 1000},
        {"item_name": "Iceworm", "item_price": 2000},
        {"item_name": "Corpseworm", "item_price": 3000},
        {"item_name": "Toxicworm", "item_price": 2000},
        {"item_name": "Sandworm", "item_price": 2000},
        {"item_name": "Beetle", "item_price": 3000},
        {"item_name": "Grasshopper", "item_price": 5000},
        {"item_name": "Wasp", "item_price": 3000},
        {"item_name": "Scallop", "item_price": 9000},
        {"item_name": "Crab", "item_price": 750},
        {"item_name": "Anchovies", "item_price": 1000},
        {"item_name": "Goldfish", "item_price": 1000},
        {"item_name": "Mackerel", "item_price": 2000},
        {"item_name": "Squid", "item_price": 2000},
        {"item_name": "Sardine", "item_price": 3000},
        {"item_name": "Eel", "item_price": 2000},
        {"item_name": "Anglerfish", "item_price": 4000},
        {"item_name": "Trout", "item_price": 9000},
        {"item_name": "Jellyfish", "item_price": 3000},
        {"item_name": "Bear Meat", "item_price": 4000},
        {"item_name": "Bass", "item_price": 30000},
        {"item_name": "Herringbone", "item_price": 6000},
        {"item_name": "Polar Bear Meat", "item_price": 6000},
        {"item_name": "Tuna", "item_price": 7000},
        {"item_name": "Lobster", "item_price": 10000},
        {"item_name": "Sea Turtle", "item_price": 13000},
        {"item_name": "Manta Ray", "item_price": 5000},
        {"item_name": "Shark", "item_price": 9000},
        {"item_name": "Orca", "item_price": 25000},
        {"item_name": "Giant Squid", "item_price": 60000},
    ],
    "Cooking (Pet Food)": [
        {"item_name": "Cooked Anchovies", "item_price": 2000},
        {"item_name": "Cooked Mackerel", "item_price": 2000},
        {"item_name": "Cooked Squid", "item_price": 2000},
        {"item_name": "Cooked Sardine", "item_price": 4000},
        {"item_name": "Cooked Eel", "item_price": 4000},
        {"item_name": "Cooked Anglerfish", "item_price": 4000},
        {"item_name": "Cooked Trout", "item_price": 4000},
        {"item_name": "Cooked Bear Meat", "item_price": 4000},
        {"item_name": "Cooked Bass", "item_price": 7000},
        {"item_name": "Cooked Polar Bear Meat", "item_price": 7000},
        {"item_name": "Cooked Tuna", "item_price": 7000},
        {"item_name": "Cooked Lobster", "item_price": 7000},
        {"item_name": "Cooked Sea Turtle", "item_price": 7000},
        {"item_name": "Cooked Manta Ray", "item_price": 7000},
        {"item_name": "Cooked Shark", "item_price": 9000},
        {"item_name": "Cooked Orca", "item_price": 9000},
        {"item_name": "Cooked Giant Squid", "item_price": 9000},
    ],
    "Spellbinding (Tomes)": [
        {"item_name": "Magic Essence", "item_price": 600},
        {"item_name": "Paper", "item_price": 300},
        {"item_name": "Book", "item_price": 1500},
        {"item_name": "Ember Tome", "item_price": 8},
        {"item_name": "Leech Tome", "item_price": 13},
        {"item_name": "Icicle Tome", "item_price": 19},
        {"item_name": "Haunt Tome", "item_price": 23},
        {"item_name": "Ignite Tome", "item_price": 30},
        {"item_name": "Drain Tome", "item_price": 35},
        {"item_name": "Freeze Tome", "item_price": 40},
        {"item_name": "Curse Tome", "item_price": 45},
        {"item_name": "Inferno Tome", "item_price": 90},
        {"item_name": "Consume Tome", "item_price": 120},
        {"item_name": "Blizzard Tome", "item_price": 100},
        {"item_name": "Torture Tome", "item_price": 250},
    ],
    "Alchemy Materials T0": [
        {"item_name": "Bat Eye", "item_price": 100},
    ],
    "Alchemy Materials T1": [
        {"item_name": "Pink Gelatin", "item_price": 5000},
        {"item_name": "Fishing Spider Eye", "item_price": 5000},
        {"item_name": "Brown Mushroom", "item_price": 5000},
        {"item_name": "Forest Spider Eye", "item_price": 5000},
        {"item_name": "Cow Skull", "item_price": 5000},
        {"item_name": "Forest Bat Eye", "item_price": 5000},
        {"item_name": "Frozen Gelatin", "item_price": 5000},
        {"item_name": "Snow Core", "item_price": 5000},
    ],
    "Alchemy Materials T2": [
        {"item_name": "Sappling Leaf", "item_price": 8000},
        {"item_name": "Ice Spider Eye", "item_price": 8000},
        {"item_name": "Cave Spider Eye", "item_price": 8000},
        {"item_name": "Skeletal Bat Eye", "item_price": 9000},
        {"item_name": "Sapphire Scarab Leg", "item_price": 10000},
        {"item_name": "Cave Bat Eye", "item_price": 9000},
        {"item_name": "Envenomed Blood", "item_price": 11000},
        {"item_name": "Raptor Claw", "item_price": 10000},
        {"item_name": "Ruby Scarab Leg", "item_price": 12000},
        {"item_name": "Forest Fiend Eye", "item_price": 10000},
        {"item_name": "Desert Raptor Claw", "item_price": 11000},
        {"item_name": "Rock Fiend Eye", "item_price": 11000},
        {"item_name": "Hornet Antenna", "item_price": 11000},
        {"item_name": "Luminant Gelatin", "item_price": 11000},
        {"item_name": "Juvenile Eye", "item_price": 10000},
        {"item_name": "Ancient Bat Eye", "item_price": 10000},
    ],
    "Alchemy Materials T3": [
        {"item_name": "Ice Raptor Claw", "item_price": 12000},
        {"item_name": "Spectral Flintstone", "item_price": 12000},
        {"item_name": "Arosite Scarab Leg", "item_price": 14000},
        {"item_name": "Shadow Flintstone", "item_price": 10000},
        {"item_name": "Phantom Flintstone", "item_price": 12000},
        {"item_name": "Spectral Fiend Eye", "item_price": 12000},
        {"item_name": "Phantom Fiend Eye", "item_price": 12000},
        {"item_name": "Magnetite Scarab Leg", "item_price": 13000},
        {"item_name": "Corrupted Eye", "item_price": 12000},
        {"item_name": "Golemite Bat Eye", "item_price": 12000},
        {"item_name": "Golemite Fiend Eye", "item_price": 12000},
        {"item_name": "Tormented Eye", "item_price": 18000},
        {"item_name": "Disdained Eye", "item_price": 22000},
        {"item_name": "Baby Dragon Spine", "item_price": 18000},
        {"item_name": "Defiled Scarab Leg", "item_price": 15000},
        {"item_name": "Rageful Eye", "item_price": 15000},
        {"item_name": "Severed Ear", "item_price": 20000},
    ],
    "Potions T0": [
        {"item_name": "Potion", "item_price": 100},
        {"item_name": "Health Potion", "item_price": 300},
        {"item_name": "Flask of Life", "item_price": 700},
        {"item_name": "Accuracy Potion", "item_price": 5000},
        {"item_name": "Deflection Potion", "item_price": 6500},
        {"item_name": "Strength Potion", "item_price": 5000},
        {"item_name": "Defense Potion", "item_price": 5000},
        {"item_name": "Rejuvenation Potion", "item_price": 5000},
        {"item_name": "Vitality Potion", "item_price": 3500},
        {"item_name": "Clarity Potion", "item_price": 6500},
    ],
    "Potions T1": [
        {"item_name": "Mining Potion", "item_price": 10000},
        {"item_name": "Woodcutting Potion", "item_price": 10000},
        {"item_name": "Fishing Potion", "item_price": 10000},
        {"item_name": "Smithing Potion", "item_price": 12000},
        {"item_name": "Crafting Potion", "item_price": 12000},
        {"item_name": "Cooking Potion", "item_price": 12000},
        {"item_name": "Spellbinding Potion", "item_price": 12000},
        {"item_name": "Taskmaster's Brew", "item_price": 8000},
    ],
    "Potions T2": [
        {"item_name": "Prospector's Brew", "item_price": 16000},
        {"item_name": "Lumberjack's Ale", "item_price": 16000},
        {"item_name": "Blacksmith's Stout", "item_price": 18000},
        {"item_name": "Artisan's Syrup", "item_price": 18000},
        {"item_name": "Angler's Elixir", "item_price": 16000},
        {"item_name": "Chef's Kiss", "item_price": 18000},
        {"item_name": "Imbuer's Wine", "item_price": 18000},
        {"item_name": "Spellpower Potion", "item_price": 20000},
        {"item_name": "Concentrated Elixir", "item_price": 16000},
        {"item_name": "Divine Clarity", "item_price": 20000},
        {"item_name": "Titan's Strength", "item_price": 15000},
        {"item_name": "Duelist's Draft", "item_price": 15000},
        {"item_name": "Stonebound Salve", "item_price": 22000},
        {"item_name": "Backlash Balm", "item_price": 15000},
        {"item_name": "Berserker Potion", "item_price": 16000},
        {"item_name": "Arcanist's Wrath", "item_price": 20000},
    ],
    "Potions T3": [
        {"item_name": "Forsworn Focus", "item_price": 20000},
        {"item_name": "Antidote", "item_price": 20000},
        {"item_name": "Frostkin Potion", "item_price": 22000},
        {"item_name": "Arctic Potion", "item_price": 20000},
        {"item_name": "Scavenger's Balm", "item_price": 20000},
        {"item_name": "Vampirism Potion", "item_price": 30000},
        {"item_name": "Assassin's Tonic", "item_price": 40000},
        {"item_name": "Auric Bloom", "item_price": 30000},
        {"item_name": "Mirrorback Brew", "item_price": 35000},
        {"item_name": "Golem's Power", "item_price": 40000},
        {"item_name": "Guardian's Bulwark", "item_price": 40000},
        {"item_name": "Quietus", "item_price": 55000},
        {"item_name": "Midas Brew", "item_price": 60000},
        {"item_name": "Featherwalk Potion", "item_price": 60000},
        {"item_name": "Sanguine Oath", "item_price": 60000},
        {"item_name": "Dance of the Undead", "item_price": 60000},
        {"item_name": "Gilded Transmutation", "item_price": 45000},
        {"item_name": "Life Elixir", "item_price": 12000},
        {"item_name": "Cloudwalk Potion", "item_price": 55000},
        {"item_name": "Distilled Extract", "item_price": 60000},
        {"item_name": "Provocation Potion", "item_price": 60000},
        {"item_name": "Strigoi's Covenant", "item_price": 60000},
        {"item_name": "Death's Rally", "item_price": 60000},
        {"item_name": "Liquid Grace", "item_price": 60000},
    ],
    "Keys & Gems": [
        {"item_name": "Prison Key", "item_price": 7000},
        {"item_name": "Blue Key", "item_price": 35000},
        {"item_name": "Green Key", "item_price": 45000},
        {"item_name": "Red Key", "item_price": 70000},
        {"item_name": "Gold Key", "item_price": 800000},
        {"item_name": "Ankh Key", "item_price": 500000},
        {"item_name": "Key to 'Corruption'", "item_price": 350000},
        {"item_name": "Key to 'Torment'", "item_price": 250000},
        {"item_name": "Key to 'Rage'", "item_price": 150000},
        {"item_name": "Key to 'Disdain'", "item_price": 125000},
        {"item_name": "Mysterious Artifact", "item_price": 150000},
        {"item_name": "Bloodied Petals", "item_price": 15000},
        {"item_name": "Sapphire", "item_price": 100000},
        {"item_name": "Ruby", "item_price": 60000},
        {"item_name": "Arosite", "item_price": 80000},
        {"item_name": "Emerald", "item_price": 70000},
        {"item_name": "Magnetite", "item_price": 200000},
        {"item_name": "Blood Diamond", "item_price": 10000000},
    ],
    "Equipment Materials": [
        {"item_name": "Spider Carapace", "item_price": 12000},
        {"item_name": "Spider Web", "item_price": 15000},
        {"item_name": "Golemite Artifact", "item_price": 1200000},
        {"item_name": "Eye of Golemite", "item_price": 2500000},
        {"item_name": "Golemite Orb", "item_price": 2500000},
        {"item_name": "Golemite Shard", "item_price": 3500000},
        {"item_name": "Golemite Slab", "item_price": 3500000},
        {"item_name": "Dragon Scales", "item_price": 15000},
        {"item_name": "Dragon Horns", "item_price": 2000000},
        {"item_name": "Dragon Eye", "item_price": 10000000},
        {"item_name": "Dragon Claws", "item_price": 22000000},
        {"item_name": "Ancient Handle", "item_price": 4000000},
        {"item_name": "Mummy Bandage", "item_price": 2000000},
        {"item_name": "Soul Jar", "item_price": 2000000},
        {"item_name": "Mummy Soul", "item_price": 4000000},
        {"item_name": "Collected Soul", "item_price": 6500000},
        {"item_name": "Slivers of Corrupt (x100)", "item_price": 8000000},
        {"item_name": "Slivers of Torment (x100)", "item_price": 7000000},
        {"item_name": "Slivers of Rage (x100)", "item_price": 5000000},
        {"item_name": "Slivers of Disdain (x100)", "item_price": 6000000},
        {"item_name": "Eye of Nydarax", "item_price": 2000000},
        {"item_name": "Leg of Nydarax", "item_price": 52000000},
        {"item_name": "Wolf Claw", "item_price": 18000000},
        {"item_name": "Wolf Fang", "item_price": 18000000},
        {"item_name": "Desert Wolf Leather", "item_price": 15000000},
    ],
    "Accessories & Mores": [
        {"item_name": "Amulet of Focus", "item_price": 2000000},
        {"item_name": "Prospector's Necklace", "item_price": 4000000},
        {"item_name": "Saving Grace", "item_price": 150000},
        {"item_name": "Cactus Gloves", "item_price": 6000000},
        {"item_name": "Infernal Ring", "item_price": 3000000},
        {"item_name": "Ancient Amulet", "item_price": 250000000},
        {"item_name": "Icy Left Half", "item_price": 2500000},
        {"item_name": "Frozen Skull", "item_price": 45000000},
        {"item_name": "Icy Right Half", "item_price": 2500000},
        {"item_name": "Balance Fragment", "item_price": 3000000},
        {"item_name": "Refined Sand", "item_price": 50000},
        {"item_name": "Glass", "item_price": 120000},
        {"item_name": "Portal Charge", "item_price": 500000},
        {"item_name": "Obsidian Thread", "item_price": 6000000},
        {"item_name": "Candy", "item_price": 325000},
        {"item_name": "Lollipop", "item_price": 1500000},
    ],
    # Add more here...
}
